package com.example.moodii.moods

import androidx.room.Entity
import androidx.room.PrimaryKey

// Defines a Room entity for storing mood entries in the database
@Entity(tableName = "mood_table")
data class MoodEntry(
    @PrimaryKey(autoGenerate = true) val id: Int = 0, // Unique ID for each entry, auto-generated by the database
    val mood: String, // Descriptive string for the mood
    val moodDetails: String, // Detailed description or notes about the mood
    val timestamp: Long = System.currentTimeMillis() // Timestamp for when the entry was created, defaults to current time
)
